$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: spam-detection-env
version: 1
description: Environment for spam detection model
dependencies:
  - conda_file: mlops/azureml/train/train-conda.yml
